package cxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-07T01:46:14.022+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://webservice/", name = "IMyService")
@XmlSeeAlso({ObjectFactory.class})
public interface IMyService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "minus", targetNamespace = "http://webservice/", className = "cxf.Minus")
    @WebMethod
    @ResponseWrapper(localName = "minusResponse", targetNamespace = "http://webservice/", className = "cxf.MinusResponse")
    public int minus(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://webservice/", className = "cxf.Add")
    @WebMethod
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://webservice/", className = "cxf.AddResponse")
    public int add(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );
}
