
package cxf;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-07T01:46:14.028+08:00
 * Generated source version: 3.1.6
 * 
 */
 
public class IMyService_MyServicePort_Server{

    protected IMyService_MyServicePort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new MyServicePortImpl();
        String address = "http://localhost:7777/fuck";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new IMyService_MyServicePort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
