
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package cxf;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-07T01:46:14.010+08:00
 * Generated source version: 3.1.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "MyServiceService",
                      portName = "MyServicePort",
                      targetNamespace = "http://webservice/",
                      wsdlLocation = "http://localhost:7777/fuck?wsdl",
                      endpointInterface = "cxf.IMyService")
                      
public class MyServicePortImpl implements IMyService {

    private static final Logger LOG = Logger.getLogger(MyServicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see cxf.IMyService#minus(int  arg0 ,)int  arg1 )*
     */
    public int minus(int arg0,int arg1) { 
        LOG.info("Executing operation minus");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            int _return = 0;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see cxf.IMyService#add(int  arg0 ,)int  arg1 )*
     */
    public int add(int arg0,int arg1) { 
        LOG.info("Executing operation add");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            int _return = 0;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
